### ISSUE TITLE
Cannot download any resources

### ISSUE THREAD

**Issue by dzulham** [mgilangjanuar/GoSCELE#2]
The app crashes when trying to download any resources.

To replicate:
1. Login
2. Open any forum or course
3. Download a document (e.g *.pdf, *.docx)

**Comment by mgilangjanuar** [comment]
What is your app version? Any error logs from Android monitor?

Update:
Please clone this repository, open from Android Studio, and run the app for view Android monitor.

**Comment by dzulham** [comment]
ORION 0.10.2
![image](https://user-images.githubusercontent.com/17609005/28056771-522d8ea0-6648-11e7-805c-e67c0212fcd1.png)
Currently, I am in no condition to be able to use Android Debugger

**Comment by mgilangjanuar** [comment]
![image](https://user-images.githubusercontent.com/3146378/28057111-4f768198-6649-11e7-9fa5-f512282789c6.png)

Is that your device?

**Comment by dzulham** [comment]
Nein. I am using Flash Plus 2. I do report the errors though.
